# Generated by Django 2.2.3 on 2019-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(to='company_service.Company'),
        ),
    ]
