# Generated by Django 2.2.4 on 2019-08-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0004_auto_20190831_1615'),
        ('users', '0003_auto_20190831_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.Company'),
        ),
    ]
