# Generated by Django 2.2.5 on 2019-09-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190919_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
