# Generated by Django 2.2.5 on 2019-10-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191015_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_group',
        ),
    ]
