version: '3.5'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: company_service
    security_opt: 
      - 'apparmor=unconfined'

  adminer:
    image: adminer
    ports:
      - 8080:8080