version: 2
jobs:
  build:
    working_directory: ~/company_service
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: company_service

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - v1-pipenv-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v1-pipenv-cache-{{ .Branch }}-
            - v1-pipenv-cache-
      - run:
          name: Installing dependencies
          command: |
            pipenv install --dev
      - save_cache:
          key: pipenv-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .venv
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
      - run:
          command: cp company_service/settings/local.py.example company_service/settings/local.py
      - run:
          command: cp company_service/settings/test.py.example company_service/settings/test.py
      - run:
          command: cp .env.example .env
      - run:
          command: pipenv run python3 manage.py makemigrations
      - run:
          command: pipenv run python3 manage.py migrate
      - run:
          name: Running tests
          command: |
            pipenv run python3 manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1