version: 2
jobs:
  build:
    working_directory: ~/company_service
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_IGNORE_VIRTUALENVS: True
          PIPENV_VENV_IN_PROJECT: True
          PIPENV_DONT_LOAD_ENV: 0
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: company_service_test

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pipenv-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v1-pipenv-cache-{{ .Branch }}-
            - v1-pipenv-cache-
      - run:
          command: |
            pipenv install --dev
      - save_cache:
          key: pipenv-cache-{{  Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .venv
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - v1-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v1-npm-cache-{{ .Branch }}-
            - v1-npm-cache-

      - run:
          command: |
            pipenv run coverage run manage.py test
        environment:
          DJANGO_SETTINGS_MODULE: 'github_integration.settings.local_base'

