# Generated by Django 2.2.4 on 2019-08-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0003_company_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='trade_name',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='company',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='industrial_sector',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
