# Generated by Django 2.2.3 on 2019-07-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0003_auto_20190720_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
