# Generated by Django 2.2.4 on 2019-09-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0005_auto_20190831_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='production_rate_per_hour',
        ),
    ]
