# Generated by Django 2.2.3 on 2019-07-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0006_productconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
