# Generated by Django 2.2.4 on 2019-09-04 11:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0007_auto_20190904_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='days_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list, size=None),
        ),
    ]
