# Generated by Django 2.2.4 on 2019-09-07 11:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0009_auto_20190906_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='days_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
