# Generated by Django 2.2.5 on 2019-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0010_auto_20190907_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='oee_goal',
        ),
        migrations.AddField(
            model_name='productionline',
            name='micro_stop_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionline',
            name='reset_production_changing_order',
            field=models.BooleanField(default=False),
        ),
    ]
