# Generated by Django 2.2.5 on 2019-09-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0011_auto_20190907_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionline',
            old_name='stop_on_production_abscence',
            new_name='stop_on_production_absence',
        ),
        migrations.AddField(
            model_name='productionline',
            name='time_to_consider_absence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
