# Generated by Django 2.2.5 on 2019-09-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0012_auto_20190907_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codegroup',
            old_name='groupType',
            new_name='group_type',
        ),
    ]
