# Generated by Django 2.2.5 on 2019-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0013_auto_20190907_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codegroup',
            name='group_type',
            field=models.CharField(choices=[('StopCode', 'Stop Code'), ('WasteCode', 'Waste Code'), ('ReworkCode', 'Rework Code')], max_length=256),
        ),
    ]
