# Generated by Django 2.2.5 on 2019-09-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0015_stopcode_was_planned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stopcode',
            old_name='was_planned',
            new_name='is_planned',
        ),
    ]
