# Generated by Django 2.2.5 on 2019-09-09 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0017_auto_20190909_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkevent',
            name='event_datetime',
            field=models.DateTimeField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='reworkevent',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder'),
        ),
        migrations.AddField(
            model_name='stopevent',
            name='event_datetime',
            field=models.DateTimeField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='stopevent',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder'),
        ),
        migrations.AddField(
            model_name='wasteevent',
            name='event_datetime',
            field=models.DateTimeField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='wasteevent',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder'),
        ),
    ]
