# Generated by Django 2.2.5 on 2019-09-10 00:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0018_auto_20190909_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event_datetime', models.DateTimeField(db_index=True, default=None)),
                ('quantity', models.IntegerField(default=0)),
                ('event_type', models.CharField(choices=[('Production', 'Production'), ('Waste', 'Waste'), ('Rework', 'Rework')], db_index=True, default='Production', max_length=20)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.Channel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.Product')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder')),
                ('stop_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.StopCode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event_datetime', models.DateTimeField(db_index=True, default=None)),
                ('state', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], db_index=True, default='On', max_length=3)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.Channel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.Product')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder')),
                ('stop_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.StopCode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stopevent',
            name='production_line',
        ),
        migrations.RemoveField(
            model_name='stopevent',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='stopevent',
            name='stop_code',
        ),
        migrations.RemoveField(
            model_name='wasteevent',
            name='production_line',
        ),
        migrations.RemoveField(
            model_name='wasteevent',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='wasteevent',
            name='waste_code',
        ),
        migrations.DeleteModel(
            name='ReworkEvent',
        ),
        migrations.DeleteModel(
            name='StopEvent',
        ),
        migrations.DeleteModel(
            name='WasteEvent',
        ),
    ]
