# Generated by Django 2.2.5 on 2019-09-10 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0020_productionevent_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionevent',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_service.Company'),
        ),
    ]
