# Generated by Django 2.2.5 on 2019-09-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0021_productionevent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionevent',
            name='rework_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ReworkCode'),
        ),
        migrations.AddField(
            model_name='productionevent',
            name='waste_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.WasteCode'),
        ),
    ]
