# Generated by Django 2.2.5 on 2019-09-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0022_auto_20190910_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_service.Company'),
        ),
    ]
