# Generated by Django 2.2.5 on 2019-09-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0023_auto_20190910_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='rework_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ReworkCode'),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='stop_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.StopCode'),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='waste_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.WasteCode'),
        ),
    ]
