# Generated by Django 2.2.5 on 2019-09-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0024_auto_20190910_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionevent',
            name='stop_code',
        ),
    ]
