# Generated by Django 2.2.5 on 2019-09-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0025_remove_productionevent_stop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='state',
            field=models.CharField(choices=[('Released', 'Released'), ('InProgress', 'In Progress'), ('Interrupted', 'Interrupted'), ('Done', 'Done')], db_index=True, default='Released', max_length=256),
        ),
    ]
