# Generated by Django 2.2.5 on 2019-09-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0025_auto_20190911_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channelType',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('Good', 'Good'), ('Rework', 'Rework'), ('Waste', 'Waste')], default='Good', max_length=256),
        ),
    ]
