# Generated by Django 2.2.5 on 2019-09-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0026_auto_20190911_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='company_service.ProductionLine'),
        ),
    ]
