# Generated by Django 2.2.5 on 2019-09-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0028_remove_collector_production_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='production_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine'),
            preserve_default=False,
        ),
    ]
