# Generated by Django 2.2.5 on 2019-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0030_remove_collector_production_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='collector_type',
            field=models.CharField(choices=[('Wise', 'Wise'), ('HW', 'HW'), ('Lora', 'Lora')], max_length=256),
        ),
    ]
