# Generated by Django 2.2.5 on 2019-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0032_auto_20190923_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='event_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Waste', 'Waste'), ('Rework', 'Rework')], db_index=True, default='Production', max_length=20),
        ),
    ]
