# Generated by Django 2.2.5 on 2019-09-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0027_auto_20190914_2330'),
        ('company_service', '0033_auto_20190923_1418'),
    ]

    operations = [
    ]
