# Generated by Django 2.2.5 on 2019-09-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0034_merge_20190923_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to='company_service.ProductionOrder'),
        ),
    ]
