# Generated by Django 2.2.5 on 2019-10-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0037_remove_manualstop_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualstop',
            name='state_event',
        ),
    ]
