# Generated by Django 2.2.5 on 2019-10-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0038_remove_manualstop_state_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.Turn'),
        ),
    ]
