# Generated by Django 2.2.6 on 2019-10-28 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0039_productionline_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_time', models.DateTimeField(db_index=True, default=None)),
                ('end_time', models.DateTimeField(db_index=True, default=None)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine')),
                ('stop_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.StopCode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
