# Generated by Django 2.2.6 on 2019-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0040_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='state',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='On', max_length=3),
        ),
    ]
