# Generated by Django 2.2.6 on 2019-10-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0041_availability_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='turn_scheme',
        ),
    ]
