# Generated by Django 2.2.6 on 2019-10-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0042_auto_20191028_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='production_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='company_service.ProductionLine'),
        ),
    ]
