# Generated by Django 2.2.6 on 2019-10-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0043_turn_production_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='turn_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.TurnScheme'),
        ),
    ]
