# Generated by Django 2.2.6 on 2019-10-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0044_productionline_turn_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='turn_scheme',
        ),
    ]
