# Generated by Django 2.2.6 on 2019-10-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0045_remove_productionline_turn_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='state',
            field=models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], default='Up', max_length=3),
        ),
    ]
