# Generated by Django 2.2.6 on 2019-10-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0046_auto_20191029_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='turn_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.TurnScheme'),
        ),
    ]
