# Generated by Django 2.2.6 on 2019-10-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0047_productionline_turn_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='state',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='On', max_length=3),
        ),
    ]
