# Generated by Django 2.2.6 on 2019-11-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0048_auto_20191030_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateevent',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_events', to='company_service.ProductionOrder'),
        ),
    ]
