# Generated by Django 2.2.6 on 2019-11-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0049_auto_20191118_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateevent',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder'),
        ),
    ]
