# Generated by Django 2.2.6 on 2019-11-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0051_remove_turn_production_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='state_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_service.StateEvent'),
        ),
    ]
