# Generated by Django 2.2.7 on 2019-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0052_availability_state_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='state',
            field=models.CharField(max_length=3),
        ),
    ]
