# Generated by Django 2.2.7 on 2019-12-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0053_auto_20191205_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='start_datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end_datetime')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
