# Generated by Django 2.2.7 on 2019-12-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0054_productionchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionchart',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='productionchart',
            name='start_datetime',
        ),
    ]
