# Generated by Django 2.2.7 on 2019-12-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0057_productionevent_production_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='state_event',
        ),
        migrations.AddField(
            model_name='stateevent',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_events', to='company_service.Availability'),
        ),
    ]
