# Generated by Django 2.2.7 on 2019-12-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0058_auto_20191211_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='state',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='stop_code',
        ),
    ]
