# Generated by Django 2.2.7 on 2019-12-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0059_auto_20191212_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='created',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='modified',
        ),
        migrations.AddField(
            model_name='availability',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='stop_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.StopCode'),
        ),
    ]
