# Generated by Django 2.2.7 on 2019-12-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0061_availability_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionchart',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productionchart',
            name='modified',
        ),
        migrations.AddField(
            model_name='productionchart',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productionchart',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
