# Generated by Django 2.2.7 on 2019-12-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0062_auto_20191217_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionchart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.Product'),
        ),
        migrations.AddField(
            model_name='productionchart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
