# Generated by Django 2.2.7 on 2019-12-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0065_auto_20191218_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WasteReworkChart',
            new_name='RejectChart',
        ),
    ]
