# Generated by Django 2.2.7 on 2019-12-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0066_auto_20191218_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionevent',
            name='production_chart',
        ),
    ]
