# Generated by Django 2.2.7 on 2019-12-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0067_remove_productionevent_production_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualstop',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manualstop',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
