# Generated by Django 2.2.7 on 2019-12-20 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0068_auto_20191219_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLineStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('production_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine')),
                ('stop_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_service.StopCode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
