# Generated by Django 2.2.7 on 2019-12-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0069_productionlinestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlinestop',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
