# Generated by Django 2.2.7 on 2019-12-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0070_productionlinestop_is_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='state',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='stop_code',
        ),
    ]
