# Generated by Django 2.2.7 on 2019-12-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0071_auto_20191223_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionchart',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='productionchart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productionchart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productionchart',
            name='start_datetime',
        ),
    ]
