# Generated by Django 2.2.7 on 2019-12-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0072_auto_20191223_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectchart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rejectchart',
            name='rework_code',
        ),
        migrations.RemoveField(
            model_name='rejectchart',
            name='state',
        ),
        migrations.RemoveField(
            model_name='rejectchart',
            name='waste_code',
        ),
    ]
