# Generated by Django 2.2.7 on 2020-01-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0073_auto_20191223_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateevent',
            name='availability',
        ),
    ]
