# Generated by Django 2.2.7 on 2020-01-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0074_remove_stateevent_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='state',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='On', max_length=3),
        ),
        migrations.AddField(
            model_name='availability',
            name='stop_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.StopCode'),
        ),
    ]
