# Generated by Django 2.2.7 on 2020-01-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0077_auto_20200110_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionchart',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productionchart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_service.Product'),
        ),
        migrations.AddField(
            model_name='productionchart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productionchart',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
