# Generated by Django 2.2.7 on 2020-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0078_auto_20200110_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionchart',
            name='event_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Waste', 'Waste'), ('Rework', 'Rework')], db_index=True, default='Production', max_length=20),
        ),
    ]
