# Generated by Django 3.0.2 on 2020-01-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0081_auto_20200114_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionLineStop',
        ),
    ]
