# Generated by Django 3.0.2 on 2020-01-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0082_delete_productionlinestop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RejectChart',
        ),
    ]
