# Generated by Django 3.0.2 on 2020-01-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0083_delete_rejectchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionChart',
        ),
    ]
