# Generated by Django 3.0.2 on 2020-01-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0084_delete_productionchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLineStop',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('company_service.availability',),
        ),
    ]
