# Generated by Django 3.0.2 on 2020-01-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0085_productionlinestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ManualStop',
        ),
    ]
