# Generated by Django 3.0.2 on 2020-01-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0086_auto_20200117_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionLineStop',
        ),
        migrations.CreateModel(
            name='ManualStop',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('company_service.availability',),
        ),
    ]
