# Generated by Django 2.2.5 on 2019-10-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='default_company',
        ),
    ]
